import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation,INCUBATION,BUILDINGS} from '../src/simulation.js';
test('infection converts once at 25 seconds; repeat bites do not restart the clock',()=>{const s=new Simulation();const e=s.entities[1];s.infect(e,0);const deadline=e.infectAt;assert.equal(deadline,INCUBATION);s.time=10;assert.equal(s.infect(e,0),false);assert.equal(e.infectAt,deadline);s.time=24.94;s.step(.05);assert.equal(e.state,'infected');s.step(.05);assert.equal(e.state,'zombie');assert.equal(s.converted,1);s.step(.05);assert.equal(s.converted,1);});
test('save/restore preserves infection deadline and population; dead infected do not resurrect',()=>{const s=new Simulation();s.infect(s.entities[1],0);s.time=12;const copy=Simulation.restore(JSON.parse(JSON.stringify(s.snapshot())));assert.equal(copy.entities[1].infectAt-copy.time,13);copy.damage(copy.entities[1],1000);copy.time=30;copy.step(.05);assert.equal(copy.entities[1].state,'dead');assert.equal(copy.entities.length,43);});
test('walls block bites and bullets; doors allow movement and every house has a route inside',()=>{const s=new Simulation();for(const b of BUILDINGS){assert.equal(s.lineOfSight({x:b.x-b.w/2-1,z:b.z},{x:b.x,z:b.z}),false);assert(s.path({x:b.x,z:b.z+b.d/2+4},{x:b.x,z:b.z}).length>0);}const d=s.doors[0];assert(s.walkable(d.x,d.z));d.open=false;assert(!s.walkable(d.x,d.z));});
test('only successful nearby bites infect',()=>{const s=new Simulation();for(const e of s.entities.slice(1)){e.x=30;e.z=30;}assert.equal(s.bite(s.player),false);const e=s.entities[1];e.x=s.player.x+1;e.z=s.player.z;assert(s.bite(s.player));assert.equal(e.state,'infected');});
test('zombie AI spreads infection and dead player transfers to another zombie',()=>{const s=new Simulation();s.entities[1].state='zombie';s.entities[1].x=1;s.entities[1].z=5;s.entities[2].x=2;s.entities[2].z=5;s.step(.05);assert.equal(s.entities[2].state,'infected');s.damage(s.player,999);s.step(.05);assert.equal(s.playerId,1);});
test('untrusted malformed saves are rejected',()=>{const s=new Simulation().snapshot();s.entities[0].x=Infinity;assert.throws(()=>Simulation.restore(s));assert.throws(()=>Simulation.restore({version:99}));});
