import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation,INCUBATION,BUILDINGS} from '../src/simulation.js';
test('infection converts once at 25 seconds; repeat bites do not restart the clock',()=>{const s=new Simulation();const e=s.entities[1];s.infect(e,0);const deadline=e.infectAt;assert.equal(deadline,INCUBATION);s.time=10;assert.equal(s.infect(e,0),false);assert.equal(e.infectAt,deadline);s.time=24.94;s.step(.05);assert.equal(e.state,'infected');s.step(.05);assert.equal(e.state,'zombie');assert.equal(s.converted,1);s.step(.05);assert.equal(s.converted,1);});
test('save/restore preserves infection deadline and population; dead infected do not resurrect',()=>{const s=new Simulation();s.infect(s.entities[1],0);s.time=12;const copy=Simulation.restore(JSON.parse(JSON.stringify(s.snapshot())));assert.equal(copy.entities[1].infectAt-copy.time,13);copy.damage(copy.entities[1],1000);copy.time=30;copy.step(.05);assert.equal(copy.entities[1].state,'dead');assert.equal(copy.entities.length,43);});
test('walls block bites and bullets; doors allow movement and every house has a route inside',()=>{const s=new Simulation();for(const b of BUILDINGS){assert.equal(s.lineOfSight({x:b.x-b.w/2-1,z:b.z},{x:b.x,z:b.z}),false);assert(s.path({x:b.x,z:b.z+b.d/2+4},{x:b.x,z:b.z}).length>0);}const d=s.doors[0];assert(s.walkable(d.x,d.z));d.open=false;assert(!s.walkable(d.x,d.z));});
test('only successful nearby bites infect',()=>{const s=new Simulation();for(const e of s.entities.slice(1)){e.x=30;e.z=30;}assert.equal(s.bite(s.player),false);const e=s.entities[1];e.x=s.player.x+1;e.z=s.player.z;assert(s.bite(s.player));assert.equal(e.state,'infected');});
test('zombie AI spreads infection and dead player transfers to another zombie',()=>{const s=new Simulation();s.entities[1].state='zombie';s.entities[1].thinkAt=0;s.entities[1].x=1;s.entities[1].z=5;s.entities[2].x=2;s.entities[2].z=5;s.step(.05);assert.equal(s.entities[2].state,'infected');s.damage(s.player,999);s.step(.05);assert.equal(s.playerId,1);});
test('untrusted malformed saves are rejected',()=>{const s=new Simulation().snapshot();s.entities[0].x=Infinity;assert.throws(()=>Simulation.restore(s));assert.throws(()=>Simulation.restore({version:99}));});

test('population is selectable and reinforcement threshold is strictly above ten, once per round',()=>{const s=new Simulation(815,20);assert.equal(s.entities.length,21);for(let i=1;i<=9;i++){s.entities[i].state='zombie';s.entities[i].everConverted=true;}s.converted=9;s.step(.05);assert.equal(s.reinforced,false);s.entities[10].state='zombie';s.entities[10].everConverted=true;s.converted=10;s.step(.05);assert.equal(s.reinforced,true);assert.equal(s.total,28);assert.equal(s.entities.length,29);const troops=s.entities.slice(-8);assert(troops.every(e=>e.role==='soldier'&&e.z<-60));s.step(.05);assert.equal(s.entities.length,29);const copy=Simulation.restore(JSON.parse(JSON.stringify(s.snapshot())));copy.step(.05);assert.equal(copy.entities.length,29);assert.equal(copy.initialPopulation,20);});
test('conversion of every NPC including reserves ends and freezes the round',()=>{const s=new Simulation(815,20);s.spawnReinforcements();for(const e of s.entities.slice(1)){s.infect(e,0);e.infectAt=.05;}s.step(.05);assert.equal(s.outcome,'win');assert.equal(s.converted,28);const before=JSON.stringify(s.snapshot());s.step(10,{x:1,z:1,bite:true});assert.equal(JSON.stringify(s.snapshot()),before);});
test('officers rally in shared houses and hold distinct defensive positions',()=>{const s=new Simulation(815,42);for(let i=0;i<1200;i++)s.step(.05);const guards=s.entities.filter(e=>e.role==='police'||e.role==='soldier');assert(guards.every(e=>e.behavior==='defend'));assert(guards.every(e=>Math.hypot(e.x-s.rally(e).x,e.z-s.rally(e).z)<1.3),JSON.stringify(guards.map(e=>({id:e.id,x:e.x,z:e.z,goal:s.rally(e)}))));assert(guards.some((e,i)=>guards.some((n,j)=>i!==j&&n.home===e.home)));});
test('maximum population preserves a bounded per-tick path workload',()=>{const s=new Simulation(815,100);for(let i=0;i<100;i++){s.step(.05);assert(s.pathCount<=2);}assert.equal(s.entities.length,101);assert(s.entities.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.z)));});
