import {Simulation,BUILDINGS,clamp} from './simulation.js';
import {View} from './view.js';
const $=id=>document.getElementById(id);let sim=new Simulation(),view,started=false,paused=true,held=false,joy={x:0,z:0},keys=new Set(),acc=0,last=performance.now(),lastSave=0,toastTimer;const menu=$('menu');
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3300);}
try{view=new View($('game'),sim);}catch(error){$('menuText').textContent='เปิดภาพสามมิติไม่สำเร็จ ลองเปิดลิงก์ใน Safari และโหลดหน้าใหม่';$('play').disabled=true;console.error(error);throw error;}
let dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('outbreak-village',1);r.onupgradeneeded=()=>r.result.createObjectStore('saves');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});dbPromise.catch(()=>{});
async function savedata(data){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('saves','readwrite');tx.objectStore('saves').put(data,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function readdata(){const db=await dbPromise;return new Promise((resolve,reject)=>{const r=db.transaction('saves').objectStore('saves').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function save(notify=true){try{await savedata(sim.snapshot());$('load').disabled=false;if(notify)toast('บันทึกเกมแล้ว');}catch{toast('บันทึกในเครื่องไม่ได้ ใช้ส่งออกเซฟเพื่อเก็บความคืบหน้า');}}
function clearInput(){keys.clear();held=false;joy={x:0,z:0};$('stick').style.transform='';}
function pause(){if(!started)return;paused=true;clearInput();menu.hidden=false;$('play').innerHTML='กลับไปเล่นต่อ <span>↗</span>';$('menuText').textContent='เกมหยุดอยู่ เวลาติดเชื้อจะเดินต่อเมื่อกลับไปเล่น';$('pauseActions').hidden=false;save(false);}
function resume(){document.activeElement?.blur();started=true;paused=false;menu.hidden=true;last=performance.now();acc=0;audioStart();}
function reset(s){sim=s;view.reset(sim);lastSave=sim.time;clearInput();resume();toast('กัดชาวบ้านใกล้ตัว แล้วรอ 25 วินาที');}
$('play').onclick=()=>{resume();if(sim.time<1)toast('เดินเข้าหาชาวบ้าน แล้วกด กัด');};$('pause').onclick=pause;
$('load').onclick=async()=>{try{const data=await readdata();if(!data){toast('ยังไม่มีเซฟในเครื่องนี้');return;}reset(Simulation.restore(data));toast('โหลดเซฟแล้ว');}catch{toast('โหลดเซฟไม่สำเร็จ ลองนำเข้าไฟล์เซฟ');}};
$('save').onclick=()=>save();$('restart').onclick=()=>{if(confirm('เริ่มรอบใหม่? เซฟอัตโนมัติจะบันทึกรอบใหม่แทน'))reset(new Simulation());};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(sim.snapshot())],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='outbreak-village-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>200000)throw Error('ไฟล์เซฟมีขนาดใหญ่เกินไป');const s=Simulation.restore(JSON.parse(await f.text()));reset(s);toast('นำเข้าเซฟแล้ว');}catch(err){toast(err.message||'ไฟล์เซฟไม่ถูกต้อง');}e.target.value='';};
$('blood').onchange=e=>{view.blood=Number(e.target.value);if(!view.blood){for(const s of view.stains){view.scene.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();}view.stains=[];}};$('quality').onchange=e=>view.quality(e.target.value==='low');
$('rotate').onclick=()=>view.yaw+=Math.PI/2;$('zoomIn').onclick=()=>view.zoom=clamp(view.zoom-4,22,52);$('zoomOut').onclick=()=>view.zoom=clamp(view.zoom+4,22,52);
$('bite').onpointerdown=e=>{e.preventDefault();if(paused)return;held=true;$('bite').setPointerCapture(e.pointerId);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('bite').addEventListener(ev,()=>held=false);
$('interact').onclick=()=>{if(!paused&&!sim.interact())toast('เข้าใกล้ประตูที่ยังไม่พังเพื่อเปิดหรือปิด');};
let joyId=null;const joystick=$('joystick');function joystickMove(e){if(e.pointerId!==joyId)return;let r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),max=35;if(len>max){dx*=max/len;dy*=max/len;}joy={x:dx/max,z:dy/max};$('stick').style.transform=`translate(${dx}px,${dy}px)`;}
joystick.onpointerdown=e=>{if(paused||joyId!==null)return;e.preventDefault();joyId=e.pointerId;joystick.setPointerCapture(joyId);joystickMove(e);};joystick.onpointermove=joystickMove;for(const ev of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(ev,e=>{if(e.pointerId===joyId){joyId=null;joy={x:0,z:0};$('stick').style.transform='';}});
window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='escape')paused?started&&resume():pause();if(!paused&&k==='e')sim.interact();if(!paused&&k==='q')view.yaw+=Math.PI/2;});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('resize',()=>view.resize());
$('game').addEventListener('wheel',e=>{e.preventDefault();view.zoom=clamp(view.zoom+e.deltaY*.025,22,52);},{passive:false});
const fingers=new Map();let pinch=0;function pinchUpdate(){if(fingers.size===2){let [a,b]=[...fingers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch)view.zoom=clamp(view.zoom*pinch/d,22,52);pinch=d;}else pinch=0;}$('game').onpointerdown=e=>{fingers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('game').setPointerCapture(e.pointerId);pinchUpdate();};$('game').onpointermove=e=>{if(fingers.has(e.pointerId)){fingers.set(e.pointerId,{x:e.clientX,y:e.clientY});pinchUpdate();}};for(const ev of ['pointerup','pointercancel'])$('game').addEventListener(ev,e=>{fingers.delete(e.pointerId);pinchUpdate();});
let audio;function audioStart(){if(!$('sound').checked)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function tone(type){if(!audio||!$('sound').checked||audio.state!=='running')return;let o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.connect(g);g.connect(audio.destination);o.type=type==='shot'?'sawtooth':'triangle';o.frequency.setValueAtTime(type==='shot'?140:type==='convert'?180:90,now);o.frequency.exponentialRampToValueAtTime(35,now+.12);g.gain.setValueAtTime(.045,now);g.gain.exponentialRampToValueAtTime(.001,now+.15);o.start();o.stop(now+.16);}
const map=$('map').getContext('2d');function hud(){const all=sim.entities,p=sim.player;let h=all.filter(e=>e.state==='human').length,i=all.filter(e=>e.state==='infected').length,z=all.filter(e=>e.state==='zombie').length;$('humans').textContent=h;$('infected').textContent=i;$('zombies').textContent=z;$('progress').style.width=`${sim.converted/sim.total*100}%`;$('objective').textContent=`กลายร่างแล้ว ${sim.converted}/${sim.total} · เสียชีวิต ${all.filter(e=>e.state==='dead').length}`;$('hp').style.width=`${p.hp/p.maxHp*100}%`;$('hptext').textContent=Math.ceil(p.hp);let near=all.filter(e=>(e.state==='human'||e.state==='infected')&&Math.hypot(e.x-p.x,e.z-p.z)<3&&sim.lineOfSight(p,e)).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];$('target').textContent=p.state==='dead'?'รอผู้ติดเชื้อกลายเป็นซอมบี้…':near?near.state==='infected'?`กำลังติดเชื้อ · ${Math.max(0,Math.ceil(near.infectAt-sim.time))} วินาที`:'ชาวบ้านอยู่ใกล้ · กดกัด':'';
 map.fillStyle='#243c30';map.fillRect(0,0,150,150);map.fillStyle='#8d957257';map.fillRect(68,4,14,142);map.fillRect(4,68,142,14);map.fillStyle='#c7c2a9';for(const b of BUILDINGS)map.fillRect(75+(b.x-b.w/2)*1.5,75+(b.z-b.d/2)*1.5,b.w*1.5,b.d*1.5);for(const e of all){if(e.state==='dead')continue;map.fillStyle=e.id===sim.playerId?'#ffffff':e.state==='zombie'?'#c8ef84':e.state==='infected'?'#efb971':e.role==='police'||e.role==='soldier'?'#88bedf':'#e8ddbd';map.beginPath();map.arc(75+e.x*1.5,75+e.z*1.5,e.id===sim.playerId?3:1.5,0,7);map.fill();}}
let frame=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.1);last=now;if(!paused){acc+=dt;let sx=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),sz=joy.z+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const input={x:sx*Math.cos(view.yaw)+sz*Math.sin(view.yaw),z:-sx*Math.sin(view.yaw)+sz*Math.cos(view.yaw),bite:held||keys.has(' ')};while(acc>=.05){sim.step(.05,input);acc-=.05;}for(const ev of sim.events){view.event(ev);if(['bite','shot','convert'].includes(ev.type))tone(ev.type);if(ev.type==='transfer')toast('ร่างเดิมถูกกำจัด · ย้ายไปควบคุมซอมบี้ที่เหลือ');if(ev.type==='win')toast('แพร่เชื้อสำเร็จทั้งหมู่บ้าน! เล่น Sandbox ต่อได้');if(ev.type==='lose'){toast('ฝูงซอมบี้ถูกกำจัดหมดแล้ว');pause();$('menuText').textContent='การระบาดถูกหยุดแล้ว เริ่มรอบใหม่เพื่อลองแผนอื่น';}}sim.events=[];if(sim.time-lastSave>20){lastSave=sim.time;save(false);}}view.update(dt,paused);if(frame++%6===0)hud();}
requestAnimationFrame(animate);readdata().then(data=>{$('load').disabled=!data;}).catch(()=>{$('load').disabled=true;});if(new URLSearchParams(location.search).has('debug'))window.__game={get sim(){return sim;},view,reset,pause,resume,get paused(){return paused;}};
