export const INCUBATION = 25;
export const BUILDINGS = [
 {x:-25,z:-25,w:11,d:10,color:0xd3c5a0,roof:0x9e5644,name:'บ้านสวน'},
 {x:-8,z:-26,w:10,d:9,color:0xdfc9a1,roof:0x476f6c,name:'ร้านขายของ'},
 {x:18,z:-24,w:13,d:11,color:0xc8cfbf,roof:0x4a6575,name:'สถานีตำรวจ'},
 {x:-28,z:-5,w:11,d:10,color:0xc8bda4,roof:0xa77145,name:'บ้านริมทาง'},
 {x:25,z:-3,w:10,d:10,color:0xd9c9b2,roof:0x8b5c50,name:'บ้านช่างไม้'},
 {x:-24,z:22,w:12,d:10,color:0xc4ccb1,roof:0x587164,name:'บ้านต้นไม้'},
 {x:-6,z:25,w:10,d:9,color:0xdbc6a9,roof:0xa56348,name:'บ้านอบขนม'},
 {x:20,z:24,w:12,d:10,color:0xd4c6a1,roof:0x516879,name:'บ้านปลายซอย'}
];
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function wallsFor(b){const x=b.x,z=b.z,w=b.w/2,d=b.d/2;return [
 {x:x-w,z:z-d,w:b.w,d:.5},{x:x-w,z:z-d,w:.5,d:b.d},{x:x+w-.5,z:z-d,w:.5,d:b.d},
 {x:x-w,z:z+d-.5,w:w-1.5,d:.5},{x:x+1.5,z:z+d-.5,w:w-1.5,d:.5}
];}
export class Simulation{
 constructor(seed=815){this.seed=seed;this.time=0;this.entities=[];this.walls=BUILDINGS.flatMap(wallsFor);this.doors=BUILDINGS.map(b=>({x:b.x,z:b.z+b.d/2-.25,open:true,broken:false}));this.events=[];this.nextId=0;this.converted=0;this.outcome='';this.playerId=0;this.create('zombie',-2,7,true);for(let i=0;i<42;i++){let x,z;if(i<3){x=-5+i*3;z=12+i*2;}else if(i<9){let b=BUILDINGS[i-3];x=b.x;z=b.z;}else if(i>34){x=11+(i-35)*2.8;z=-15;}else{do{x=this.random()*76-38;z=this.random()*74-37;}while(!this.walkable(x,z));}this.create(i>=40?'soldier':i>=35?'police':'villager',x,z);}this.total=42;}
 random(){this.seed=(1664525*this.seed+1013904223)>>>0;return this.seed/4294967296;}
 create(role,x,z,player=false){const e={id:this.nextId++,role,state:role==='zombie'?'zombie':'human',x,z,angle:0,hp:player?150:role==='soldier'?115:90,maxHp:player?150:role==='soldier'?115:90,infectAt:null,everConverted:false,cool:0,route:[],repath:0,goal:null,move:0,fear:.7+this.random()*.6,pose:0};this.entities.push(e);return e;}
 get player(){return this.entities.find(e=>e.id===this.playerId);}
 walkable(x,z,r=.38,doors=true){if(Math.abs(x)>46-r||Math.abs(z)>46-r)return false;for(const b of this.walls)if(x>b.x-r&&x<b.x+b.w+r&&z>b.z-r&&z<b.z+b.d+r)return false;if(doors)for(const d of this.doors)if(!d.open&&!d.broken&&Math.abs(x-d.x)<1.5+r&&Math.abs(z-d.z)<.25+r)return false;return true;}
 lineOfSight(a,b){let steps=Math.ceil(distance(a,b)/.45);for(let i=1;i<steps;i++){let t=i/steps;if(!this.walkable(a.x+(b.x-a.x)*t,a.z+(b.z-a.z)*t,0))return false;}return true;}
 moveEntity(e,dx,dz){let ox=e.x,oz=e.z;if(this.walkable(e.x+dx,e.z))e.x+=dx;if(this.walkable(e.x,e.z+dz))e.z+=dz;e.move=Math.hypot(e.x-ox,e.z-oz);if(e.move>.0001)e.angle=Math.atan2(dx,dz);}
 infect(e,source){if(e.state!=='human')return false;e.state='infected';e.infectAt=this.time+INCUBATION;e.pose=.45;this.events.push({type:'bite',x:e.x,z:e.z,source});return true;}
 bite(attacker){if(!attacker||attacker.state!=='zombie'||attacker.cool>0)return false;const candidates=this.entities.filter(e=>e.state==='human'&&distance(e,attacker)<2.05&&this.lineOfSight(attacker,e)).sort((a,b)=>distance(a,attacker)-distance(b,attacker));if(!candidates.length)return false;let e=candidates[0];attacker.angle=Math.atan2(e.x-attacker.x,e.z-attacker.z);attacker.pose=.55;attacker.cool=1.1;return this.infect(e,attacker.id);}
 damage(e,amount,source){if(e.state==='dead')return;e.hp=Math.max(0,e.hp-amount);e.pose=.18;this.events.push({type:'hit',x:e.x,z:e.z,source});if(e.hp===0){e.state='dead';e.infectAt=null;e.route=[];this.events.push({type:'death',x:e.x,z:e.z});}}
 interact(){let p=this.player;if(!p||p.state==='dead')return false;let d=this.doors.find(d=>distance(d,p)<3);if(!d)return false;if(d.broken)return false;d.open=!d.open;this.events.push({type:'door',x:d.x,z:d.z,open:d.open});return true;}
 path(a,b){const offset=47,size=95;const key=(x,z)=>(z+offset)*size+x+offset;const sx=Math.round(a.x),sz=Math.round(a.z),tx=Math.round(clamp(b.x,-45,45)),tz=Math.round(clamp(b.z,-45,45));const start=key(sx,sz),end=key(tx,tz);let open=[{x:sx,z:sz,k:start,g:0,f:0}],seen=new Set(),cost=new Map([[start,0]]),parent=new Map();let best=start,bestDist=Infinity;let steps=0;while(open.length&&steps++<1800){let bi=0;for(let i=1;i<open.length;i++)if(open[i].f<open[bi].f)bi=i;const n=open.splice(bi,1)[0];if(seen.has(n.k))continue;seen.add(n.k);let dd=Math.abs(n.x-tx)+Math.abs(n.z-tz);if(dd<bestDist){bestDist=dd;best=n.k;}if(n.k===end)break;for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){let x=n.x+dx,z=n.z+dz,k=key(x,z);if(seen.has(k)||!this.walkable(x,z,.42,false))continue;if(dx&&dz&&(!this.walkable(n.x+dx,n.z,.42,false)||!this.walkable(n.x,n.z+dz,.42,false)))continue;let g=n.g+(dx&&dz?1.414:1);if(g>=(cost.get(k)??Infinity))continue;cost.set(k,g);parent.set(k,n.k);open.push({x,z,k,g,f:g+Math.hypot(x-tx,z-tz)});}}
 let route=[],k=best;while(k!==start&&parent.has(k)){route.push({x:k%size-offset,z:Math.floor(k/size)-offset});k=parent.get(k);}return route.reverse();}
 navigate(e,goal,speed,dt){e.repath-=dt;if(e.repath<=0||!e.route.length){e.route=this.path(e,goal);e.repath=.8+this.random()*.7;}for(const d of this.doors)if(!d.open&&distance(e,d)<2.3){d.open=true;if(e.state==='zombie')d.broken=true;this.events.push({type:'door',x:d.x,z:d.z,open:true});}let next=e.route[0];if(!next){e.move=0;return;}let dx=next.x-e.x,dz=next.z-e.z,len=Math.hypot(dx,dz);if(len<.22){e.route.shift();return;}let step=Math.min(speed*dt,len);this.moveEntity(e,dx/len*step,dz/len*step);}
 step(dt,input={x:0,z:0,bite:false}){this.time+=dt;for(const e of this.entities){e.cool=Math.max(0,e.cool-dt);e.pose=Math.max(0,e.pose-dt);e.move=0;if(e.state==='infected'&&this.time+1e-8>=e.infectAt){e.state='zombie';e.infectAt=null;e.everConverted=true;this.converted++;e.goal=null;e.route=[];this.events.push({type:'convert',x:e.x,z:e.z});}}
 let p=this.player;if(p?.state==='dead'){let next=this.entities.find(e=>e.state==='zombie');if(next){this.playerId=next.id;p=next;this.events.push({type:'transfer'});}}
 const living=this.entities.filter(e=>e.state!=='dead'),zombies=living.filter(e=>e.state==='zombie'),humans=living.filter(e=>e.state==='human'||e.state==='infected');
 for(const e of living){if(e.state==='dead')continue;if(e.id===this.playerId&&e.state==='zombie'){let len=Math.hypot(input.x,input.z);if(len>.01)this.moveEntity(e,input.x/Math.max(1,len)*5.4*dt,input.z/Math.max(1,len)*5.4*dt);if(input.bite)this.bite(e);continue;}
 if(e.state==='infected'&&e.infectAt-this.time<3)continue;
 if(e.state==='zombie'){let target=humans.filter(h=>h.state==='human'&&distance(h,e)<17&&this.lineOfSight(e,h)).sort((a,b)=>distance(a,e)-distance(b,e))[0];if(target){e.goal={x:target.x,z:target.z};if(distance(e,target)<2)this.bite(e);else this.navigate(e,e.goal,3.1,dt);}else this.wander(e,1.4,dt);}
 else{let threat=zombies.filter(z=>distance(z,e)<(e.role==='villager'?11:18)&&this.lineOfSight(e,z)).sort((a,b)=>distance(a,e)-distance(b,e))[0];if(threat&&(e.role==='police'||e.role==='soldier')){let d=distance(e,threat);e.angle=Math.atan2(threat.x-e.x,threat.z-e.z);if(d<15&&e.cool<=0){e.cool=e.role==='soldier'?.95:1.6;this.events.push({type:'shot',x:e.x,z:e.z,tx:threat.x,tz:threat.z});if(this.random()<.7)this.damage(threat,e.role==='soldier'?13:10,e.id);}if(d<5){let v={x:e.x+(e.x-threat.x)*2,z:e.z+(e.z-threat.z)*2};this.navigate(e,v,2.5,dt);}else if(d>12)this.navigate(e,threat,2.4,dt);}
 else if(threat){let dx=e.x-threat.x,dz=e.z-threat.z,len=Math.hypot(dx,dz)||1;let goal={x:clamp(e.x+dx/len*10,-44,44),z:clamp(e.z+dz/len*10,-44,44)};this.navigate(e,goal,(e.state==='infected'?2.65:3.5)*e.fear,dt);}else this.wander(e,e.state==='infected'?1.2:1.55,dt);}}
 if(this.converted>=this.total&&!this.outcome){this.outcome='win';this.events.push({type:'win'});}else if(!zombies.length&&!living.some(e=>e.state==='infected')&&!this.outcome){this.outcome='lose';this.events.push({type:'lose'});}}
 wander(e,speed,dt){if(!e.goal||distance(e,e.goal)<1.5){if(this.random()<.35){let b=BUILDINGS[Math.floor(this.random()*BUILDINGS.length)];e.goal={x:b.x,z:b.z};}else{let x,z;do{x=this.random()*80-40;z=this.random()*80-40;}while(!this.walkable(x,z));e.goal={x,z};}e.route=[];}this.navigate(e,e.goal,speed,dt);}
 snapshot(){return {version:1,seed:this.seed,time:this.time,entities:this.entities.map(e=>({...e,route:[]})),doors:this.doors,playerId:this.playerId,converted:this.converted,total:this.total,nextId:this.nextId,outcome:this.outcome};}
 static restore(data){if(!data||data.version!==1||!Array.isArray(data.entities)||data.entities.length!==43||!Array.isArray(data.doors)||data.doors.length!==8||!Number.isFinite(data.time)||data.time<0)throw Error('รูปแบบไฟล์เซฟไม่ถูกต้อง');const ids=new Set();for(const e of data.entities){if(!Number.isInteger(e.id)||ids.has(e.id)||!['human','infected','zombie','dead'].includes(e.state)||!['villager','police','soldier','zombie'].includes(e.role)||![e.x,e.z,e.hp,e.maxHp,e.cool,e.angle,e.fear].every(Number.isFinite)||Math.abs(e.x)>47||Math.abs(e.z)>47||e.hp<0||e.maxHp<=0||e.hp>e.maxHp||(e.state==='infected'&&!Number.isFinite(e.infectAt)))throw Error('ข้อมูลตัวละครในเซฟไม่ถูกต้อง');ids.add(e.id);}if(!ids.has(data.playerId)||data.total!==42||!Number.isInteger(data.converted)||data.converted<0||data.converted>42||!Number.isFinite(data.seed))throw Error('ข้อมูลรอบเกมไม่ถูกต้อง');for(let i=0;i<8;i++){const d=data.doors[i],b=BUILDINGS[i];if(d.x!==b.x||d.z!==b.z+b.d/2-.25||typeof d.open!=='boolean'||typeof d.broken!=='boolean')throw Error('ข้อมูลประตูไม่ถูกต้อง');}let sim=new Simulation();Object.assign(sim,{seed:data.seed,time:data.time,playerId:data.playerId,converted:data.converted,total:42,nextId:43,outcome:['win','lose'].includes(data.outcome)?data.outcome:''});sim.entities=data.entities.map(e=>({...e,route:[],repath:0,goal:null,pose:0,move:0}));sim.doors=data.doors.map(d=>({...d}));return sim;}
}
