import * as T from '../vendor/three.module.js';
import {BUILDINGS} from './simulation.js';
export class View{
 constructor(canvas,sim){this.sim=sim;this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;this.scene=new T.Scene();this.scene.background=new T.Color(0xaec7b3);this.scene.fog=new T.Fog(0xaec7b3,65,125);this.camera=new T.PerspectiveCamera(42,1,.1,160);this.yaw=.65;this.zoom=34;this.look=new T.Vector3(-2,0,7);this.actors=new Map();this.actorBatches=new Map();this.houses=[];this.fx=[];this.stains=[];this.materials=new Map();this.scene.add(new T.HemisphereLight(0xe7f2d6,0x58634b,2.2));const sun=new T.DirectionalLight(0xffe4b7,3.2);sun.position.set(-22,40,14);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-52,right:52,top:52,bottom:-52,near:1,far:110});sun.shadow.bias=-.0007;sun.shadow.normalBias=.06;this.scene.add(sun);this.sun=sun;this.buildWorld();this.batchScenery();this.blood=2;this.resize();this.ring=new T.Mesh(new T.RingGeometry(.75,.9,40),new T.MeshBasicMaterial({color:0xd7ff85,side:T.DoubleSide,transparent:true,opacity:.85}));this.ring.rotation.x=-Math.PI/2;this.scene.add(this.ring);}
 mat(color){if(!this.materials.has(color))this.materials.set(color,new T.MeshStandardMaterial({color,roughness:.88}));return this.materials.get(color);}
 box(w,h,d,color,x=0,y=0,z=0,parent=this.scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),this.mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 ball(r,color,x,y,z,parent=this.scene,detail=1){const m=new T.Mesh(new T.IcosahedronGeometry(r,detail),this.mat(color));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
 label(text){const c=document.createElement('canvas');c.width=256;c.height=64;let ctx=c.getContext('2d');ctx.fillStyle='#f1e5c5';ctx.fillRect(0,0,256,64);ctx.fillStyle='#354a3c';ctx.font='bold 28px Tahoma, sans-serif';ctx.textAlign='center';ctx.fillText(text,128,43);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return new T.MeshBasicMaterial({map:tex});}
 buildWorld(){this.box(120,.5,120,0x839572,0,-.33,0);this.box(11,.04,94,0xb3a38b,0,-.04,0);this.box(94,.04,9,0xb3a38b,0,-.035,0);this.box(7,.035,82,0xc6b99c,0,-.01,0);this.box(83,.035,6,0xc6b99c,0,-.005,0);
 for(let i=-43;i<45;i+=3){this.box(.12,.015,.85,0xe1d7b9,0,.025,i);}
 for(let n=0;n<BUILDINGS.length;n++){let b=BUILDINGS[n],g=new T.Group();g.position.set(b.x,0,b.z);this.scene.add(g);this.box(b.w+.5,.28,b.d+.5,0x7d8170,0,.1,0,g);this.box(b.w-.5,.05,b.d-.5,0xc5a47c,0,.26,0,g);const walls=[];walls.push(this.box(b.w,3,.35,b.color,0,1.75,-b.d/2,g));walls.push(this.box(.35,3,b.d,b.color,-b.w/2,1.75,0,g));walls.push(this.box(.35,3,b.d,b.color,b.w/2,1.75,0,g));walls.push(this.box(b.w/2-1.5,3,.35,b.color,-b.w/4-.75,1.75,b.d/2,g));walls.push(this.box(b.w/2-1.5,3,.35,b.color,b.w/4+.75,1.75,b.d/2,g));this.box(3,.55,.4,b.color,0,3,b.d/2,g);
 const cut=new T.Group();g.add(cut);const shape=new T.Shape();shape.moveTo(-b.w/2-.6,0);shape.lineTo(0,2.6);shape.lineTo(b.w/2+.6,0);shape.closePath();const geo=new T.ExtrudeGeometry(shape,{depth:b.d+1.2,bevelEnabled:false});const roof=new T.Mesh(geo,this.mat(b.roof));roof.position.set(0,3.25,-b.d/2-.6);roof.castShadow=true;roof.receiveShadow=true;cut.add(roof);this.box(.18,.14,b.d+1.4,0x3f514b,0,5.86,0,cut);this.box(.9,1.9,.85,0x797b6d,b.w*.23,4.9,-b.d*.2,cut);this.box(1.15,.2,1.12,0x575e55,b.w*.23,5.83,-b.d*.2,cut);
 for(const x of [-b.w*.32,b.w*.32]){this.box(1.9,1.55,.12,0x596552,x,1.95,b.d/2+.21,g);this.box(1.58,1.22,.14,0x88adad,x,1.95,b.d/2+.3,g);this.box(.08,1.26,.17,0xe6dbc0,x,1.95,b.d/2+.38,g);this.box(1.65,.08,.17,0xe6dbc0,x,1.95,b.d/2+.38,g);this.box(2.1,.2,.5,0x827c65,x,1.14,b.d/2+.33,g);this.box(1.75,.25,.34,0x5b7c4a,x,1.34,b.d/2+.39,g);}
 for(const z of [-b.d*.25,b.d*.25]){this.box(.12,1.5,1.7,0x536c63,b.w/2+.2,1.9,z,g);this.box(.14,1.18,1.4,0x96b5ad,b.w/2+.28,1.9,z,g);}
 let door=this.box(2.8,2.35,.2,0x6b6953,0,1.45,b.d/2,g);let sign=new T.Mesh(new T.PlaneGeometry(3.8,.9),this.label(b.name));sign.position.set(0,3.02,b.d/2+.25);g.add(sign);
 this.box(2.8,.6,1.2,0x638377,-b.w*.23,.58,-b.d*.23,g);this.box(2.8,.7,.35,0x759487,-b.w*.23,1.04,-b.d*.23-.5,g);this.box(2,.15,1.3,0x947752,1,.9,-.5,g);for(let x of [.2,1.8])for(let z of [-1,0])this.box(.12,.65,.12,0x715d44,x,.55,z,g);this.box(1.4,1.7,.65,0x9c835f,b.w/2-1.1,1.15,-b.d/2+1,g);const rug=this.box(3.3,.015,2.5,0xb59876,0,.302,.9,g);rug.receiveShadow=true;
 this.houses.push({g,cut,walls,door,b});let start=b.z+b.d/2;this.box(3.6,.04,Math.max(2,Math.abs(start)),0xc1b391,b.x,.01,start/2);this.box(3.6,.15,1,0xbfbba4,b.x,.1,start+.6);
 }
 // Hand-placed foliage frames the village; deterministic decorations survive reloads.
 let seed=53;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};
 for(let i=0;i<72;i++){let x=rand()*102-51,z=rand()*102-51;if(Math.abs(x)<7||Math.abs(z)<6||BUILDINGS.some(b=>Math.abs(x-b.x)<b.w/2+2&&Math.abs(z-b.z)<b.d/2+3))continue;const h=2+rand()*1.4;const trunk=new T.Mesh(new T.CylinderGeometry(.22,.38,h,7),this.mat(0x776952));trunk.position.set(x,h/2,z);trunk.castShadow=true;this.scene.add(trunk);let c=[0x58784c,0x668451,0x7d915b][i%3];this.ball(1.8+rand()*.6,c,x,h+1,z);this.ball(1.3,c,x+1.1,h+.7,z+.4);this.ball(1.15,0x7e995a,x-.9,h+1.3,z-.4);}
 for(let i=0;i<70;i++){let x=rand()*93-46,z=rand()*93-46;if(Math.abs(x)<6||Math.abs(z)<5||BUILDINGS.some(b=>Math.abs(x-b.x)<b.w/2+1&&Math.abs(z-b.z)<b.d/2+1))continue;let rock=this.ball(.25+rand()*.3,0x9b9c85,x,.2,z,undefined,0);rock.scale.y=.55;}
 for(const x of [-8,8])for(const z of [-14,14]){this.box(.15,3.5,.15,0x4d5b51,x,1.7,z);this.box(.65,.7,.65,0xdaca9d,x,3.6,z);this.box(.9,.13,.9,0x45594b,x,4,z);}
 // Village well and benches create a readable center.
 const well=new T.Mesh(new T.CylinderGeometry(1.35,1.5,.8,12),this.mat(0x8e9588));well.position.set(9,.4,8);well.castShadow=true;this.scene.add(well);const water=new T.Mesh(new T.CircleGeometry(1.08,20),this.mat(0x59898d));water.rotation.x=-Math.PI/2;water.position.set(9,.82,8);this.scene.add(water);for(const x of [7.6,10.4])this.box(.18,2.7,.18,0x827052,x,1.4,8);this.box(3.4,.22,2.1,0x67745d,9,2.8,8);
 for(const [x,z] of [[-8,7],[8,-7]]){this.box(2.5,.18,.8,0x8b7250,x,.6,z);this.box(2.5,.65,.15,0x9d8258,x,1,z-.4);for(const a of [-.9,.9])this.box(.12,.6,.65,0x526354,x+a,.3,z);}
 }
 actor(e){const root=new T.Group(),body=new T.Group();root.add(body);const shirtColor=e.role==='police'?0x405876:e.role==='soldier'?0x677454:[0xbb775b,0x6d91a1,0xd0ad65,0x857795,0x97a37e][e.id%5];const skin=this.mat(e.state==='zombie'?0x91ad67:0xdbb48e).clone();const shirt=this.box(.62,.64,.4,shirtColor,0,1.01,0,body);shirt.geometry.dispose();shirt.geometry=new T.CapsuleGeometry(.26,.34,4,8);const head=new T.Mesh(new T.SphereGeometry(.28,10,8),skin);head.scale.set(.9,1.06,.92);head.position.y=1.65;head.castShadow=true;body.add(head);this.box(.42,.14,.37,e.role==='police'?0x364a66:e.role==='soldier'?0x66704b:0x514a3c,0,1.88,-.03,body);this.box(.09,.06,.05,0x283c31,-.1,1.67,.235,body);this.box(.09,.06,.05,0x283c31,.1,1.67,.235,body);const arms=[],legs=[];for(const s of [-1,1]){const arm=new T.Group();arm.position.set(s*.4,1.27,0);body.add(arm);this.box(.18,.42,.2,shirtColor,0,-.17,0,arm);const hand=new T.Mesh(new T.SphereGeometry(.12,7,6),skin);hand.position.set(0,-.46,0);arm.add(hand);arms.push(arm);const leg=new T.Group();leg.position.set(s*.17,.72,0);body.add(leg);this.box(.21,.55,.23,0x4d5959,0,-.25,0,leg);this.box(.25,.16,.4,0x394a42,0,-.56,.07,leg);legs.push(leg);}let gun=null;if(e.role==='police'||e.role==='soldier'){gun=this.box(.13,.14,e.role==='soldier'?.65:.35,0x303d3c,.01,-.42,.2,arms[1]);}
 const halo=new T.Mesh(new T.RingGeometry(.4,.5,20),new T.MeshBasicMaterial({color:0xe7b975,side:T.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=.08;this.scene.add(halo);return {root,body,skin,arms,legs,gun,halo};}
 event(ev){if(['bite','hit','death'].includes(ev.type)&&this.blood){const count=(ev.type==='death'?10:6)*this.blood;for(let i=0;i<count;i++){if(this.fx.length>95){let old=this.fx.shift();this.scene.remove(old.mesh);old.mesh.geometry.dispose();}const mesh=new T.Mesh(new T.SphereGeometry(.045+Math.random()*.035,4,3),this.mat(0x933d38));mesh.position.set(ev.x,ev.type==='death'?.4:1.15,ev.z);this.scene.add(mesh);this.fx.push({mesh,v:new T.Vector3((Math.random()-.5)*3,1+Math.random()*2,(Math.random()-.5)*3),life:.7,type:'blood'});}const m=new T.Mesh(new T.CircleGeometry(ev.type==='death'?.7:.22+Math.random()*.22,12),new T.MeshBasicMaterial({color:0x71372f,transparent:true,opacity:.65,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}));m.rotation.x=-Math.PI/2;m.rotation.z=Math.random()*6;m.scale.y=.7;const floor=BUILDINGS.some(b=>Math.abs(ev.x-b.x)<b.w/2&&Math.abs(ev.z-b.z)<b.d/2)?.3:0;m.position.set(ev.x,floor+.035,ev.z);this.scene.add(m);this.stains.push({mesh:m,life:60});if(this.stains.length>70){const o=this.stains.shift();this.scene.remove(o.mesh);o.mesh.geometry.dispose();o.mesh.material.dispose();}}
 if(ev.type==='shot'){let geo=new T.BufferGeometry().setFromPoints([new T.Vector3(ev.x,1.25,ev.z),new T.Vector3(ev.tx,1.1,ev.tz)]);const mesh=new T.Line(geo,new T.LineBasicMaterial({color:0xffdc96,transparent:true,opacity:.8}));this.scene.add(mesh);this.fx.push({mesh,type:'shot',life:.08});}}
 update(dt,paused=false){const p=this.sim.player;for(const e of this.sim.entities){let a=this.actors.get(e.id);if(!a){a=this.actor(e);this.actors.set(e.id,a);}const floor=BUILDINGS.some(b=>Math.abs(e.x-b.x)<b.w/2&&Math.abs(e.z-b.z)<b.d/2)?.28:0;a.root.position.set(e.x,floor+(e.state==='dead'?.13:0),e.z);a.root.rotation.y=e.angle;a.body.rotation.x=e.state==='dead'?-Math.PI/2:0;a.body.position.y=e.state==='dead'?0:Math.sin(this.sim.time*9+e.id)*Math.min(e.move*2,.06);a.skin.color.setHex(e.state==='zombie'?0x91ad67:e.state==='infected'?0xbeb687:0xdbb48e);const stride=e.move>.001?Math.sin(this.sim.time*10+e.id)*.6:0;for(let i=0;i<2;i++){a.legs[i].rotation.x=e.state==='dead'?0:stride*(i?1:-1);a.arms[i].rotation.x=e.state==='zombie'?-1.1+(e.pose>0?-.5:stride*.2):-stride*(i?1:-1);a.arms[i].rotation.z=e.state==='infected'&&e.infectAt-this.sim.time<3?Math.sin(this.sim.time*25)*.3:0;}a.halo.position.set(e.x,floor+.08,e.z);a.halo.visible=e.state==='infected';a.halo.scale.setScalar(e.state==='infected'?1+(25-(e.infectAt-this.sim.time))/25:1);if(a.gun)a.gun.visible=e.state!=='zombie'&&e.state!=='dead';}
 if(p){const floor=BUILDINGS.some(b=>Math.abs(p.x-b.x)<b.w/2&&Math.abs(p.z-b.z)<b.d/2)?.28:0;this.ring.position.set(p.x,floor+.06,p.z);this.ring.visible=p.state==='zombie';this.look.lerp(new T.Vector3(p.x,.4,p.z),1-Math.exp(-dt*5));}this.camera.position.set(this.look.x+Math.sin(this.yaw)*this.zoom,this.zoom*.92,this.look.z+Math.cos(this.yaw)*this.zoom);this.camera.lookAt(this.look);
 for(let i=0;i<this.houses.length;i++){const h=this.houses[i];const inside=p&&Math.abs(p.x-h.b.x)<h.b.w/2+.1&&Math.abs(p.z-h.b.z)<h.b.d/2+.1;h.cut.visible=!inside;for(let j=2;j<h.walls.length;j++){const w=h.walls[j];if(!w.userData.unique){w.material=w.material.clone();w.material.transparent=true;w.userData.unique=true;}w.material.opacity=T.MathUtils.lerp(w.material.opacity,inside?.13:1,Math.min(1,dt*8));w.material.depthWrite=!inside;}h.door.visible=!this.sim.doors[i].open;}
 if(!paused){for(let i=this.fx.length-1;i>=0;i--){let f=this.fx[i];f.life-=dt;if(f.v){f.v.y-=dt*8;f.mesh.position.addScaledVector(f.v,dt);if(f.mesh.position.y<.04)f.life=0;}if(f.life<=0){this.scene.remove(f.mesh);f.mesh.geometry.dispose();if(f.type==='shot')f.mesh.material.dispose();this.fx.splice(i,1);}}for(let i=this.stains.length-1;i>=0;i--){const s=this.stains[i];s.life-=dt;s.mesh.material.opacity=Math.min(.65,s.life/12*.65);if(s.life<=0){this.scene.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();this.stains.splice(i,1);}}}
 this.updateActorBatches();this.renderer.render(this.scene,this.camera);}
 batchScenery(){this.scene.updateMatrixWorld(true);const dynamic=new Set();for(const h of this.houses)h.g.traverse(o=>dynamic.add(o));const groups=new Map();const originals=[];this.scene.traverse(o=>{if(o.isMesh&&!dynamic.has(o)){const key=o.material.uuid;if(!groups.has(key))groups.set(key,{material:o.material,positions:[],normals:[]});const group=groups.get(key),geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(o.matrixWorld);group.positions.push(...geo.attributes.position.array);group.normals.push(...geo.attributes.normal.array);geo.dispose();originals.push(o);}});for(const o of originals){o.removeFromParent();o.geometry.dispose();}for(const group of groups.values()){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(group.positions,3));geo.setAttribute('normal',new T.Float32BufferAttribute(group.normals,3));geo.computeBoundingSphere();const mesh=new T.Mesh(geo,group.material);mesh.castShadow=true;mesh.receiveShadow=true;this.scene.add(mesh);}}
 updateActorBatches(){for(const b of this.actorBatches.values())b.count=0;for(const a of this.actors.values()){a.root.updateMatrixWorld(true);a.root.traverse(o=>{if(!o.isMesh||!o.visible)return;const key=o.geometry.type+JSON.stringify(o.geometry.parameters);let b=this.actorBatches.get(key);if(!b){const mesh=new T.InstancedMesh(o.geometry,new T.MeshStandardMaterial({color:0xffffff,roughness:.88}),200);mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);mesh.frustumCulled=false;mesh.castShadow=true;mesh.receiveShadow=true;this.scene.add(mesh);b={mesh,count:0};this.actorBatches.set(key,b);}b.mesh.setMatrixAt(b.count,o.matrixWorld);b.mesh.setColorAt(b.count,o.material.color);b.count++;});}for(const b of this.actorBatches.values()){b.mesh.count=b.count;b.mesh.instanceMatrix.needsUpdate=true;if(b.mesh.instanceColor)b.mesh.instanceColor.needsUpdate=true;}}
 reset(sim){this.sim=sim;for(const a of this.actors.values()){this.scene.remove(a.root);this.scene.remove(a.halo);a.halo.geometry.dispose();a.root.traverse(o=>{if(o.geometry)o.geometry.dispose();});a.skin.dispose();a.halo.material.dispose();}this.actors.clear();for(const b of this.actorBatches.values()){this.scene.remove(b.mesh);b.mesh.dispose();b.mesh.material.dispose();}this.actorBatches.clear();for(const f of [...this.fx,...this.stains]){this.scene.remove(f.mesh);f.mesh.geometry.dispose();if(f.type!=='blood')f.mesh.material.dispose();}this.fx=[];this.stains=[];this.look.set(sim.player.x,0,sim.player.z);}
 resize(){let w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 quality(low){this.renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.5));this.renderer.shadowMap.enabled=!low;this.resize();}
}
