import * as T from '../vendor/three.module.js';
import {BUILDINGS,insideHouse,CAMPS,FLOOR_HEIGHT,wallsFor,furnitureFor,OBSTACLES,stairsFor,TERRACES,groundHeight,transportFor,WORLD_HALF,VILLAGES,FARMS} from './world.js?v=0.5';
import {RoundedBoxGeometry} from '../vendor/RoundedBoxGeometry.js';
export class View{
 constructor(canvas,sim){this.sim=sim;this.renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(1);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.shadowMap.autoUpdate=false;this.renderer.shadowMap.needsUpdate=true;this.resolution=1;this.qualityMode='auto';this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.13;this.scene=new T.Scene();this.scene.background=new T.Color(0x9de0ea);this.scene.fog=new T.Fog(0x9de0ea,100,235);this.camera=new T.PerspectiveCamera(42,1,.1,300);this.yaw=.65;this.zoom=43;this.look=new T.Vector3(-2,0,7);this.actors=new Map();this.actorBatches=new Map();this.houses=[];this.fx=[];this.stains=[];this.materials=new Map();this.clay=new T.MeshStandardMaterial({color:0xffffff,roughness:1,vertexColors:true});this.temp=new T.Vector3();this.animTime=0;this.scene.add(new T.HemisphereLight(0xffeff3,0x82b8ca,2.5));const sun=new T.DirectionalLight(0xffe5cc,2.6);sun.position.set(-90,170,75);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-150,right:150,top:150,bottom:-150,near:1,far:340});sun.shadow.bias=-.0007;sun.shadow.normalBias=.06;this.scene.add(sun);this.sun=sun;this.buildWorld();this.batchScenery();this.blood=2;this.resize();this.ring=new T.Mesh(new T.RingGeometry(.75,.9,40),new T.MeshBasicMaterial({color:0xd7ff85,side:T.DoubleSide,transparent:true,opacity:.85}));this.ring.rotation.x=-Math.PI/2;this.scene.add(this.ring);this.setupBlobs();this.setupCityBatches();}
 mat(color){if(!this.materials.has(color))this.materials.set(color,new T.MeshStandardMaterial({color,roughness:1}));return this.materials.get(color);}
 box(w,h,d,color,x=0,y=0,z=0,parent=this.scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),this.mat(color));m.geometry.parameters={width:w,height:h,depth:d,segments:2};m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 ball(r,color,x,y,z,parent=this.scene,detail=1){const m=new T.Mesh(new T.SphereGeometry(r,detail===0?8:12,detail===0?6:8),this.mat(color));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
 label(text){const c=document.createElement('canvas');c.width=256;c.height=64;let ctx=c.getContext('2d');ctx.fillStyle='#f1e5c5';ctx.fillRect(0,0,256,64);ctx.fillStyle='#354a3c';ctx.font='bold 28px Tahoma, sans-serif';ctx.textAlign='center';ctx.fillText(text,128,43);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return new T.MeshBasicMaterial({map:tex});}
 buildWorld(){
 this.box(WORLD_HALF*2+4,3,WORLD_HALF*2+4,0x7ebfc9,0,-1.65,0);this.box(WORLD_HALF*2,.2,WORLD_HALF*2,0xa6e0dc,0,-.15,0);
 for(let q=-120;q<=120;q+=30){this.box(7,.06,282,0x74bccb,q,-.01,0);this.box(282,.06,7,0x74bccb,0,0,q);for(let k=-135;k<=135;k+=6){this.box(.12,.02,2.3,0xecf7e8,q,.04,k);this.box(2.3,.02,.12,0xecf7e8,k,.045,q);}}
 for(const b of BUILDINGS){const g=new T.Group();g.position.set(b.x,0,b.z);this.scene.add(g);const levels=[];
 if(b.kind==='house')this.box(24,.08,26,0xb3d6a5,0,-.02,0,g);
 this.box(21,.24,24,0xcde8e4,0,.02,0,g);
 for(let f=0;f<=b.floors;f++){const level=new T.Group();level.position.y=f*FLOOR_HEIGHT;g.add(level);const interior=new T.Group();level.add(interior);const front=new T.Group();level.add(front);
 // Separate floor slabs leave a real opening above both stair flights.
 for(const [x,z,w,d] of [[-6.5,0,5,20],[6.5,0,5,20],[0,-8.4,8,3.2],[0,8.4,8,3.2]])this.box(w,.2,d,f===b.floors?0xb3d8d9:0xf5e8cf,x,.08,z,level);
 if(f===0)this.box(7.8,.2,13.5,0xf5e8cf,0,.08,0,level);else{const lane=(f-1)%2?2:-2;for(const [left,right] of [[-4,lane-1],[lane+1,4]])this.box(right-left,.2,13.6,0xf5e8cf,(left+right)/2,.08,0,level);}
 for(const w of wallsFor(b,f)){const h=f===b.floors?1:3.4;const par=w.interior?interior:w.z>b.z+9||w.x>b.x+8?front:level;this.box(w.w,h,w.d,b.color,w.x+w.w/2-b.x,h/2+.18,w.z+w.d/2-b.z,par);}
 if(f<b.floors){// Perimeter trim leaves the stairwell open.
 for(const [x,z,w,d] of [[0,-10,18.5,.35],[0,10,18.5,.35],[-9,0,.35,20],[9,0,.35,20]])this.box(w,.22,d,0xffecde,x,3.48,z,level);
 for(const x of [-6.5,-3,3,6.5]){this.box(1.6,1.9,.16,0xfce4db,x,1.95,10.24,front);this.box(1.24,1.57,.17,0x629fb9,x,1.95,10.34,front);this.box(.08,1.6,.1,0xe4e9e8,x,1.95,10.46,front);}
 for(const z of [-7,-3,3,7]){this.box(.16,1.9,1.6,0xffe5dc,9.2,1.95,z,front);this.box(.17,1.57,1.24,0x70acbc,9.3,1.95,z,front);}
 for(const r of furnitureFor(b,f)){this.box(r.w,.55,r.d,0xe9adbe,r.x+r.w/2-b.x,.5,r.z+r.d/2-b.z,interior);this.box(r.w,.7,.2,0xf6c9d6,r.x+r.w/2-b.x,.85,r.z+r.d/2-b.z-.5,interior);}
 const st=stairsFor(b,f);for(let i=0;i<18;i++){const t=(i+.5)/18,z=st.a.z+(st.b.z-st.a.z)*t-b.z;this.box(1.8,FLOOR_HEIGHT/18,.69,0xe5d2bb,st.a.x-b.x,(i+1)/18*FLOOR_HEIGHT,z,interior);}
 this.box(.12,1,12,0xf5eedb,st.a.x-b.x+.96,2,-0,interior).rotation.x=(st.b.z-st.a.z)>0?-.28:.28;
 }else{for(const x of [-1.1,0,1.1])this.box(.7,.035,1,0xf1bd78,x,.21,9,level);this.box(2,1.3,2,0xb8dfe8,5,.8,-6,level);const tank=new T.Mesh(new T.CylinderGeometry(1.15,1.15,2,12),this.mat(0x8fcddd));tank.position.set(-6,1.25,-6);level.add(tank);}
 levels.push({group:level,interior,front,floor:f});}
 let roof=null;if(b.kind==='house'){roof=new T.Group();roof.position.y=b.floors*FLOOR_HEIGHT;g.add(roof);const shape=new T.Shape();shape.moveTo(-9.8,.15);shape.lineTo(0,3.5);shape.lineTo(9.8,.15);shape.closePath();const mesh=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:21.5,bevelEnabled:false}),this.mat(b.roof));mesh.position.z=-10.75;roof.add(mesh);this.box(1,2,1,0xe3cab6,5,3,-4,roof);this.box(1.25,.18,1.25,0xbca394,5,4,-4,roof);for(const x of [-6.5,6.5])this.box(2.8,.2,1.5,0xf9ebd4,x,2.9,10.9,levels[0].front);}
 this.houses.push({g,b,levels,roof,cut:levels[b.floors].group});}
 for(const r of OBSTACLES){if(r.camp||r.truck)continue;if(r.fence){const color=0xf3e7ca;for(const y of [.5,1])this.box(r.w,.15,r.d,color,r.x+r.w/2,y,r.z+r.d/2);const horizontal=r.w>r.d,length=horizontal?r.w:r.d;for(let i=0;i<=Math.ceil(length/1.6);i++){const t=i/Math.ceil(length/1.6);this.box(.16,1.3,.16,color,r.x+(horizontal?r.w*t:r.w/2),.65,r.z+(horizontal?r.d/2:r.d*t));}continue;}const x=r.x+r.w/2,z=r.z+r.d/2;if(r.hay){const base=groundHeight(x,z);this.box(r.w,.85,r.d,0xe5c878,x,base+.45,z);for(const offset of [-.5,.5])this.box(.09,.87,r.d+.04,0xb69459,x+offset,base+.45,z);continue;}if(r.bench){this.box(r.w,.18,r.d,0xc49b91,x,.65,z);this.box(r.w,.6,.12,0xdeafa4,x,1,z-.35);for(const side of [-1,1])this.box(.15,.65,.65,0x719495,x+side,.32,z);continue;}if(r.lamp){this.box(.45,4.5,.45,0x719ba6,x,2.25,z);this.box(1,.3,1,0xffe3b5,x,4.6,z);this.box(1.1,.15,1.1,0x87b2bc,x,4.8,z);continue;}if(r.tree){const base=groundHeight(x,z),forest=!!r.forest;this.box(r.w,2.5,r.d,0xab8074,x,base+1.25,z);for(let i=0;i<(forest?3:5);i++)this.ball(forest?1.3:1.1,(forest?[0x91b894,0xa7c6a0,0xb9caaa]:[0xffd16d,0xf3bd62,0xf7d986])[i%3],x+Math.sin(i*2.4)*.7,base+3.1+(i%2)*.6,z+Math.cos(i*2.4)*.7,undefined,forest?0:1);}else{const col=r.x<0?0xffd77e:0xf1a7bb;this.box(2,.9,3.8,col,x,.65,z);this.box(1.65,.7,1.8,col,x,1.4,z);this.box(1.5,.5,.06,0x8cb4c5,x,1.4,z+.93);for(const dx of [-1,1])for(const dz of [-1.1,1.1])this.ball(.35,0x63778e,x+dx,.38,z+dz);}}
 for(const p of TERRACES){const pos=[],norm=[];for(let x=p.x-p.w/2;x<p.x+p.w/2;x++)for(let z=p.z-p.d/2;z<p.z+p.d/2;z++){for(const [dx,dz] of [[0,0],[0,1],[1,1],[0,0],[1,1],[1,0]])pos.push(x+dx,groundHeight(x+dx,z+dz)+.06,z+dz);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(pos,3));geo.computeVertexNormals();const park=new T.Mesh(geo,this.mat(0xa9d6aa));park.receiveShadow=true;this.scene.add(park);}
 for(const farm of FARMS){const positions=[];for(let x=farm.x-11;x<farm.x+11;x+=2)for(let z=farm.z-11;z<farm.z+11;z+=2)for(const [dx,dz] of [[0,0],[0,2],[2,2],[0,0],[2,2],[2,0]])positions.push(x+dx,groundHeight(x+dx,z+dz)+.07,z+dz);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.computeVertexNormals();this.scene.add(new T.Mesh(geo,this.mat(0xb5a17b)));
 for(let ix=0;ix<8;ix++)for(let iz=0;iz<8;iz++){const x=farm.x-8.4+ix*2.4,z=farm.z-8.4+iz*2.4;if(OBSTACLES.some(r=>r.hay&&x>r.x-.5&&x<r.x+r.w+.5&&z>r.z-.5&&z<r.z+r.d+.5))continue;const base=groundHeight(x,z),h=1.35+(ix+iz)%3*.15;this.box(.09,h,.09,0x82986a,x,base+h/2,z);for(const side of [-1,1]){const leaf=this.box(.9,.055,.3,0x9bb278,x+side*.34,base+h*.57,z);leaf.rotation.z=side*.5;}this.ball(.15,0xf1cf76,x+.13,base+h*.75,z,undefined,0);}}
 for(const c of CAMPS){this.box(10,.2,7,0x9bbfbd,c.x,.1,c.z);for(const side of [-1,1]){this.box(2,1.3,2,0x83a5a3,c.x+side*5,.7,c.z);this.box(2.2,.4,2.2,0x6f9598,c.x+side*5,1.55,c.z);}// Transport is parked beside the dispatch lane, never on a soldier's spawn point.
 const transport=transportFor(c);this.box(2.5,1.4,4.5,0x779ea8,transport.x,.9,transport.z);this.box(2.3,1.1,1.6,0x97c0c7,transport.x,2,transport.z+1);for(const dx of [-1.3,1.3])for(const dz of [-1.5,1.5])this.ball(.4,0x536877,transport.x+dx,.45,transport.z+dz);
 this.box(.12,5,.12,0xe9ebd7,c.x,2.5,c.z);this.box(2,1,.05,0xf7c1bf,c.x+1,4.5,c.z);}
 }

 actor(e){const root=new T.Group(),body=new T.Group();root.add(body);const shirtColor=e.role==='police'?0x405876:e.role==='soldier'?0x677454:[0xbb775b,0x6d91a1,0xd0ad65,0x857795,0x97a37e][e.id%5];const skin=this.mat(e.state==='zombie'?0x91ad67:0xdbb48e).clone();const shirt=this.box(.62,.64,.4,shirtColor,0,1.01,0,body);shirt.geometry.dispose();shirt.geometry=new T.CapsuleGeometry(.26,.34,4,8);const head=new T.Mesh(new T.SphereGeometry(.28,10,8),skin);head.scale.set(.9,1.06,.92);head.position.y=1.65;head.castShadow=true;body.add(head);this.box(.42,.14,.37,e.role==='police'?0x364a66:e.role==='soldier'?0x66704b:0x514a3c,0,1.88,-.03,body);this.box(.09,.06,.05,0x283c31,-.1,1.67,.235,body);this.box(.09,.06,.05,0x283c31,.1,1.67,.235,body);const arms=[],legs=[];for(const s of [-1,1]){const arm=new T.Group();arm.position.set(s*.4,1.27,0);body.add(arm);this.box(.18,.42,.2,shirtColor,0,-.17,0,arm);const hand=new T.Mesh(new T.SphereGeometry(.12,7,6),skin);hand.position.set(0,-.46,0);arm.add(hand);arms.push(arm);const leg=new T.Group();leg.position.set(s*.17,.72,0);body.add(leg);this.box(.21,.55,.23,0x4d5959,0,-.25,0,leg);this.box(.25,.16,.4,0x394a42,0,-.56,.07,leg);legs.push(leg);}let gun=null;if(e.role==='police'||e.role==='soldier'){gun=this.box(.13,.14,e.role==='soldier'?.65:.35,0x303d3c,.01,-.42,.2,arms[1]);}
 const halo=new T.Mesh(new T.RingGeometry(.4,.5,20),new T.MeshBasicMaterial({color:0xe7b975,side:T.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=.08;this.scene.add(halo);const parts=[];root.traverse(o=>{if(o.isMesh){o.userData.batchKey=o.geometry.type+JSON.stringify(o.geometry.parameters);parts.push(o);}});return {role:e.role,root,body,skin,arms,legs,gun,halo,parts,visible:true};}
 event(ev){if(Number.isFinite(ev.x)&&Math.hypot(ev.x-this.look.x,ev.z-this.look.z)>38)return;if(['bite','hit','death'].includes(ev.type)&&this.blood){const count=(ev.type==='death'?5:3)*this.blood;for(let i=0;i<count;i++){if(this.fx.length>32){let old=this.fx.shift();this.scene.remove(old.mesh);old.mesh.geometry.dispose();}const mesh=new T.Mesh(new T.SphereGeometry(.045+Math.random()*.035,4,3),this.mat(0x933d38));mesh.position.set(ev.x,(ev.y||0)+(ev.type==='death'?.4:1.15),ev.z);this.scene.add(mesh);this.fx.push({mesh,v:new T.Vector3((Math.random()-.5)*3,1+Math.random()*2,(Math.random()-.5)*3),life:.7,type:'blood'});}const m=new T.Mesh(new T.CircleGeometry(ev.type==='death'?.7:.22+Math.random()*.22,12),new T.MeshBasicMaterial({color:0x71372f,transparent:true,opacity:.65,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}));m.rotation.x=-Math.PI/2;m.rotation.z=Math.random()*6;m.scale.y=.7;const floor=(ev.y||0)+.2;m.position.set(ev.x,floor+.035,ev.z);this.scene.add(m);this.stains.push({mesh:m,life:60});if(this.stains.length>32){const o=this.stains.shift();this.scene.remove(o.mesh);o.mesh.geometry.dispose();o.mesh.material.dispose();}}
 if(ev.type==='shot'){let geo=new T.BufferGeometry().setFromPoints([new T.Vector3(ev.x,(ev.y||0)+1.25,ev.z),new T.Vector3(ev.tx,(ev.ty||0)+1.1,ev.tz)]);const mesh=new T.Line(geo,new T.LineBasicMaterial({color:0xffdc96,transparent:true,opacity:.8}));this.scene.add(mesh);this.fx.push({mesh,type:'shot',life:.08});}}
 update(dt,paused=false,alpha=1){
  this.animTime+=paused?0:dt;const p=this.sim.player;const t=paused?1:alpha;
  for(const a of this.actors.values()){a.visible=false;a.halo.visible=false;}
  const activeBuilding=p?insideHouse(p.x,p.z):-1, activeFloor=p?.floor||0;
  let detailed=0,lod=0;for(const e of this.sim.entities){const dx=e.x-this.look.x,dz=e.z-this.look.z,range=dx*dx+dz*dz,building=insideHouse(e.x,e.z);
   if(range>this.zoom*this.zoom*2.7||building>=0&&(building!==activeBuilding||e.floor!==activeFloor))continue;
   const x=T.MathUtils.lerp(e.px??e.x,e.x,t),z=T.MathUtils.lerp(e.pz??e.z,e.z,t),floor=T.MathUtils.lerp(e.py??e.y,e.y,t)+.2;
   if(range>400||detailed>=96){if(e.state!=='dead'&&lod<16384){const down=e.downUntil>this.sim.time;this.lodTransform.rotation.set(down?Math.PI/2:0,e.angle,0);this.lodTransform.position.set(x,floor+(down?.3:.8),z);this.lodTransform.updateMatrix();this.crowd.setMatrixAt(lod,this.lodTransform.matrix);this.crowd.setColorAt(lod++,this.tempColor.setHex(e.state==='zombie'?0x93b96b:e.role==='soldier'?0x718c89:e.role==='police'?0x6e93bd:0xe0a4bc));}continue;}
   detailed++;let a=this.actors.get(e.id);if(!a){if(this.actors.size>=128){const old=[...this.actors].find(([id,o])=>!o.visible&&o.role===e.role);if(old){a=old[1];this.actors.delete(old[0]);} }if(!a)a=this.actor(e);this.actors.set(e.id,a);}a.visible=true;
   a.halo.visible=e.state==='infected';a.root.position.set(x,floor+(e.state==='dead'?.13:0),z);
   let delta=Math.atan2(Math.sin(e.angle-a.root.rotation.y),Math.cos(e.angle-a.root.rotation.y));a.root.rotation.y+=delta*Math.min(1,dt*15);
   const down=e.state==='dead'||e.downUntil>this.sim.time,feeding=e.feeding>this.sim.time;
   const lean=e.fall?-.4:down?-Math.PI/2:feeding?.7+Math.sin(this.animTime*13)*.12:e.state==='infected'?.22:0;a.body.rotation.x=T.MathUtils.lerp(a.body.rotation.x,lean,Math.min(1,dt*9));a.body.position.y=down?.25+(e.state==='infected'?Math.sin(this.animTime*3+e.id)*.015:0):feeding?-.25:Math.sin(this.animTime*9+e.id)*Math.min(e.move*2,.05);
   a.skin.color.setHex(e.state==='zombie'?0xa1b985:e.state==='infected'?0xc3bd96:0xe0b99e);
   const stride=e.move>.001?Math.sin(this.animTime*(e.state==='infected'?6:10)+e.id)*(e.state==='infected'?.3:.55):0;
   for(let i=0;i<2;i++){a.legs[i].rotation.x=e.fall?Math.sin(this.animTime*14+i)*.8:down?0:stride*(i?1:-1);a.arms[i].rotation.x=e.state==='zombie'?-1.1+(e.pose>0?-.5:stride*.2):-stride*(i?1:-1);a.arms[i].rotation.z=feeding?Math.sin(this.animTime*15+i)*.3:0;}
   a.halo.position.set(x,floor+.08,z);if(a.gun)a.gun.visible=e.state!=='zombie'&&e.state!=='dead';
  }
  this.crowd.count=lod;this.crowd.instanceMatrix.needsUpdate=true;if(this.crowd.instanceColor)this.crowd.instanceColor.needsUpdate=true;
  if(p){const x=T.MathUtils.lerp(p.px??p.x,p.x,t),z=T.MathUtils.lerp(p.pz??p.z,p.z,t),floor=T.MathUtils.lerp(p.py??p.y,p.y,t)+.2;this.ring.position.set(x,floor+.06,z);this.ring.visible=p.state==='zombie';this.temp.set(x,floor+.4,z);this.look.lerp(this.temp,1-Math.exp(-dt*7));}
  this.camera.position.set(this.look.x+Math.sin(this.yaw)*this.zoom,this.look.y+this.zoom*.92,this.look.z+Math.cos(this.yaw)*this.zoom);this.camera.lookAt(this.look);
  for(const h of this.houses){const inside=activeBuilding===h.b.id;const dx=h.b.x-(p?.x||0),dz=h.b.z-(p?.z||0),along=dx*Math.sin(this.yaw)+dz*Math.cos(this.yaw),across=Math.abs(dx*Math.cos(this.yaw)-dz*Math.sin(this.yaw));const occludes=!inside&&along>0&&along<this.zoom+12&&across<9*Math.abs(Math.cos(this.yaw))+10*Math.abs(Math.sin(this.yaw))+1;const cap=occludes?Math.max(0,Math.floor(((p?.y||0)+.92*Math.max(0,along-13)-4)/FLOOR_HEIGHT)):99;if(h.roof)h.roof.visible=!inside&&cap>=h.b.floors;h.g.visible=Math.hypot(h.b.x-this.look.x,h.b.z-this.look.z)<85;for(const l of h.levels){l.group.visible=inside?l.floor<=activeFloor:l.floor<=cap;l.interior.visible=inside&&(l.floor===activeFloor||p.stair&&l.floor===Math.min(p.stair.a.floor,p.stair.c.floor));l.front.visible=!(inside&&l.floor===activeFloor);}}
  this.updateDoors(activeBuilding,activeFloor);

  if(!paused){for(let i=this.fx.length-1;i>=0;i--){let f=this.fx[i];f.life-=dt;if(f.v){f.v.y-=dt*8;f.mesh.position.addScaledVector(f.v,dt);if(f.mesh.position.y<.04)f.life=0;}if(f.life<=0){this.scene.remove(f.mesh);f.mesh.geometry.dispose();if(f.type==='shot')f.mesh.material.dispose();this.fx.splice(i,1);}}for(let i=this.stains.length-1;i>=0;i--){const s=this.stains[i];s.life-=dt;s.mesh.material.opacity=Math.min(.65,s.life/12*.65);if(s.life<=0){this.scene.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();this.stains.splice(i,1);}}}
  this.updateActorBatches();this.renderer.render(this.scene,this.camera);
 }
 mergeClay(meshes,parent=this.scene,unique=false){
  const positions=[],normals=[],colors=[];const inverse=new T.Matrix4().copy(parent.matrixWorld).invert();
  for(const o of meshes){const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(new T.Matrix4().multiplyMatrices(inverse,o.matrixWorld));const pos=geo.attributes.position.array,norm=geo.attributes.normal.array,c=o.material.color;for(let i=0;i<pos.length;i++)positions.push(pos[i]);for(let i=0;i<norm.length;i++)normals.push(norm[i]);for(let i=0;i<pos.length/3;i++)colors.push(c.r,c.g,c.b);geo.dispose();o.removeFromParent();o.geometry.dispose();}
  const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('normal',new T.Float32BufferAttribute(normals,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.computeBoundingSphere();const mesh=new T.Mesh(geo,unique?this.clay.clone():this.clay);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;
 }
 batchScenery(){
 this.scene.updateMatrixWorld(true);const dynamic=new Set();
 for(const h of this.houses)if(h.roof){const meshes=[];h.roof.traverse(o=>{if(o.isMesh)meshes.push(o);});this.mergeClay(meshes,h.roof);h.roof.traverse(o=>dynamic.add(o));}
 for(const h of this.houses)for(const l of h.levels){for(const group of [l.interior,l.front]){const meshes=[];group.traverse(o=>{if(o.isMesh)meshes.push(o);});if(meshes.length)this.mergeClay(meshes,group);group.traverse(o=>dynamic.add(o));}const meshes=l.group.children.filter(o=>o.isMesh);if(meshes.length)this.mergeClay(meshes,l.group);l.group.traverse(o=>dynamic.add(o));}
 this.scene.updateMatrixWorld(true);const chunks=new Map();this.scene.traverse(o=>{if(!o.isMesh||dynamic.has(o)||o.material.map)return;const p=new T.Vector3();o.getWorldPosition(p);const k=`${Math.floor(p.x/30)},${Math.floor(p.z/30)}`;if(!chunks.has(k))chunks.set(k,[]);chunks.get(k).push(o);});for(const group of chunks.values())this.mergeClay(group);
 }

 setupBlobs(){const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const ctx=canvas.getContext('2d'),gradient=ctx.createRadialGradient(16,16,1,16,16,16);gradient.addColorStop(0,'rgba(56,49,36,0.28)');gradient.addColorStop(1,'rgba(56,49,36,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,32,32);const tex=new T.CanvasTexture(canvas);this.blobs=new T.InstancedMesh(new T.PlaneGeometry(1.7,1.4),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}),256);this.blobs.frustumCulled=false;this.blobTransform=new T.Object3D();this.blobTransform.rotation.x=-Math.PI/2;this.scene.add(this.blobs);}
 updateActorBatches(){
  let blobs=0;for(const b of this.actorBatches.values())b.count=0;
  for(const a of this.actors.values()){if(!a.visible)continue;this.blobTransform.position.set(a.root.position.x,a.root.position.y+.04,a.root.position.z);this.blobTransform.updateMatrix();this.blobs.setMatrixAt(blobs++,this.blobTransform.matrix);a.root.updateMatrixWorld(true);for(const o of a.parts){if(!o.visible)continue;const key=o.userData.batchKey;let b=this.actorBatches.get(key);if(!b){const mesh=new T.InstancedMesh(o.geometry,new T.MeshStandardMaterial({color:0xffffff,roughness:1}),512);mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);mesh.frustumCulled=false;mesh.castShadow=false;mesh.receiveShadow=true;this.scene.add(mesh);b={mesh,count:0};this.actorBatches.set(key,b);}b.mesh.setMatrixAt(b.count,o.matrixWorld);b.mesh.setColorAt(b.count,o.material.color);b.count++;}}
  this.blobs.count=blobs;this.blobs.instanceMatrix.needsUpdate=true;for(const b of this.actorBatches.values()){b.mesh.count=b.count;b.mesh.instanceMatrix.needsUpdate=true;if(b.mesh.instanceColor)b.mesh.instanceColor.needsUpdate=true;}
 }
 setupCityBatches(){
 this.tempColor=new T.Color();this.lodTransform=new T.Object3D();this.crowd=new T.InstancedMesh(new T.CapsuleGeometry(.3,.9,2,5),this.mat(0xffffff),16384);this.crowd.instanceMatrix.setUsage(T.DynamicDrawUsage);this.crowd.frustumCulled=false;this.scene.add(this.crowd);
 this.doorBatch=new T.InstancedMesh(new T.BoxGeometry(1,1,1),this.mat(0x849fae),1200);this.doorBatch.frustumCulled=false;this.scene.add(this.doorBatch);this.doorBars=new T.InstancedMesh(new T.BoxGeometry(1,.1,.1),new T.MeshBasicMaterial({color:0xffffff}),1200);this.doorBars.frustumCulled=false;this.scene.add(this.doorBars);this.doorTransform=new T.Object3D();
 }
 updateDoors(building,floor){let n=0,bars=0;const p=this.sim.player;for(const d of this.sim.doors){if(d.broken||d.open||d.floor!==floor||!d.exterior&&d.building!==building||Math.hypot(d.x-this.look.x,d.z-this.look.z)>70)continue;const o=this.doorTransform;o.position.set(d.x,d.floor*FLOOR_HEIGHT+(d.gate?.7:1.4),d.z);o.rotation.set(0,0,0);o.scale.set(d.w,d.gate?1.3:2.6,d.d);o.updateMatrix();this.doorBatch.setMatrixAt(n++,o.matrix);if(p&&Math.hypot(p.x-d.x,p.z-d.z)<8){o.position.y=d.floor*FLOOR_HEIGHT+(d.gate?1.7:3);o.scale.set(2*d.hp/100,1,1);o.rotation.y=this.yaw;o.updateMatrix();this.doorBars.setMatrixAt(bars,o.matrix);this.doorBars.setColorAt(bars++,this.tempColor.setHex(d.hp>40?0xa6d98c:0xf38f91));}}this.doorBatch.count=n;this.doorBatch.instanceMatrix.needsUpdate=true;this.doorBars.count=bars;this.doorBars.instanceMatrix.needsUpdate=true;if(this.doorBars.instanceColor)this.doorBars.instanceColor.needsUpdate=true;
 }
 reset(sim){this.sim=sim;for(const a of this.actors.values()){this.scene.remove(a.root);this.scene.remove(a.halo);a.halo.geometry.dispose();a.root.traverse(o=>{if(o.geometry)o.geometry.dispose();});a.skin.dispose();a.halo.material.dispose();}this.actors.clear();for(const b of this.actorBatches.values()){this.scene.remove(b.mesh);b.mesh.dispose();b.mesh.material.dispose();}this.actorBatches.clear();for(const f of [...this.fx,...this.stains]){this.scene.remove(f.mesh);f.mesh.geometry.dispose();if(f.type!=='blood')f.mesh.material.dispose();}this.fx=[];this.stains=[];this.look.set(sim.player.x,0,sim.player.z);}
 resize(){let w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 quality(mode){this.qualityMode=mode;this.resolution=mode==='low'?.7:mode==='normal'?1.25:1;this.renderer.setPixelRatio(this.resolution);this.resize();}
 adapt(fps){if(this.qualityMode!=='auto')return;let next=this.resolution;if(fps<52)next=Math.max(.65,next-.08);else if(fps>59)next=Math.min(1,next+.03);if(Math.abs(next-this.resolution)>.01){this.resolution=next;this.renderer.setPixelRatio(next);this.resize();}}
}
